In [1]:
from aoc_utils import *

import pandas as pd
import numpy as np

from aocd import get_data, submit

In [2]:
year = 2024
day = 13

In [3]:
dat = get_data(day=day, year=year, block=True)

In [ ]:
'''
P = n*A + m*B

n = (P - m*B)/A

so 

(P - m*B) % A == 0

so 

(P % A) == (m*B % A)

find P % A
find k st (k*B % A) = (P % A)
find t st (t*B % A) = 0

solutions can be generated by:
m := (t*i + k)

# we need to find an m which solves both equations
P = x*A + y*B

P = (x, y)(
'''

In [ ]:
14927552949614

In [72]:
(p[0]*b[1] - p[1]*a[1]) / det

-67.29565753002771

In [69]:
p

array([9086,  311])

In [78]:
9086*(26/det) - 311*(57/det)
print(26/det, 57/det)

-0.008007391438250694 -0.01755466584539575


In [77]:
det = (a[0]*b[1] - a[1]*b[0])
print(p, np.linalg.inv(ab))
p @ np.linalg.inv(ab) 


[9086  311] [[-0.00800739  0.01755467]
 [ 0.02063443 -0.00677549]]


array([-66.33785032, 157.39451802])

In [106]:
# P = n*A + m*B
# n + m < 100
# min (3*n + m)
# d = parse(dat, ints)
# 
def get_rems(p, a, b):
    rems = {}
    p_rem = p % a
    b_rem = b % a
    i = 1
    while b_rem not in rems.values():
        rems[i] = b_rem
        b_rem = (b_rem + b) % a
        i += 1
    return rems

def is_possible(p, a, b, rems):
    p_rem = p % a
    return (a - p_rem) in rems
        
def find_min_soln2(p, a, b):
    rem
    rems_0 = get_rems(p[0], a[0], b[0])
    print(rems_0)
    rems_1 = get_rems(p[1], a[1], b[1])
    print(rems_1)
    for i in range((max(rems_0)+1)*(max(rems_1)+1)):
        i0 = i%b[0]
        i1 = i%b[1]
        if i0 not in rems_0:
            continue
        if i1 not in rems_1:
            continue
        r0 = rems_0[i0]
        r1 = rems_1[i1]
        if ((i*r0) % a[0]) - (p[0] % a[0]) != 0:
            continue
        if ((i*r1) % a[1]) - (p[1] % a[1]) != 0:
            continue
        return ((p[0] - i*b[0])//a[0], i)
    

def find_min_soln(p, a, b):
    for m in range(101):
        if not (((p[0] - m *b[0]) % a[0]) == 0):
            continue
        if not (((p[1] - m *b[1]) % a[1]) == 0):
            continue
        if (p[0] - m*b[0])/a[0] != (p[1] - m*b[1])/a[1]:
            continue
        return ((p[0] - m*b[0])//a[0], m)

def solve_sym(p, a, b):
    p = np.array(p)
    a = np.array(a)
    b = np.array(b)

p1 = 0
for i, d in enumerate(dat.split('\n\n')):
    a, b, p = parse(d, ints)
    # p = np.array(p)
    ab = np.array([a, b])
    # det = (a[0]*b[1] - a[1]*b[0])
    # print(det, np.linalg.det(ab))
    # n = (p[0]*b[1] - p[1]*a[1])
    # m = (- p[0]*b[0] + p[1]*a[0])
    # print()
    # print(n/det, m/det)
    n, m = (10000000000000 + np.array(p)) @ np.linalg.inv(ab)
    # print(n,m)
    if abs(n - np.round(n)) > 1e-5:
        continue
    if abs(m - np.round(m)) > 1e-5:
        continue
        
    # if not (m % det) == 0:
    #     continue
    # if not (n % det) == 0:
    #     continue
    # n /= det
    # m /= det
    # if find_min_soln(p, a, b):
    #     print('linalg',n,m)
    #     print('brute', find_min_soln(p, a, b))
    p1 += 3*np.round(n) + 1*np.round(m)


p1 

14927552949614.0

In [8]:

p1 = 0
for i, d in enumerate(dat.split('\n\n')):
    a, b, p = parse(d, ints)
    
    p = 10000000000000 + np.array(p)
    ab = np.array([a, b])
    det = (a[0]*b[1] - a[1]*b[0])
    n = (p[0]*b[1] - p[1]*b[0])
    m = (- p[0]*a[1] + p[1]*a[0])
    if not (m % det) == 0:
        continue
    if not (n % det) == 0:
        continue
    n //= det
    m //= det
    p1 += 3*n + 1*m


p1 

89013607072065

In [29]:
p = np.array(p)
a = np.array(a)
b = np.array(b)
p, a, b

(array([9086,  311]), array([22, 57]), array([67, 26]))

In [54]:
ab = np.array([a,b])
n,m = p @ np.linalg.inv(ab)
print(n, m)
np.isclose(soln, np.round(soln))

-66.33785032337543 157.3945180166307


array([ True,  True])

In [40]:
np.isclose?

Signature:       np.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
Call signature:  np.isclose(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function isclose at 0x105659ee0>
File:            ~/miniconda3/lib/python3.11/site-packages/numpy/core/numeric.py
Docstring:      
Returns a boolean array where two arrays are element-wise equal within a
tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

.. warning:: The default `atol` is not appropriate for comparing numbers
             that are much smaller than one (see Notes).

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Notes).
equal_nan : bool
    Whether to compare NaN's as 

In [ ]:
#(73, 15) (29, 42) (7707, 4539)
#found soln 73 82

In [13]:
73*73 + 82*29, 73*15 + 82*42

(7707, 4539)

In [15]:
7707 % 73, 82*29 % 73

(42, 42)

In [19]:
82 % 29

24

In [13]:
submit(p1, day=day, part='a', year=year)

That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]


In [8]:
submit(p2, day=day, part='b', year=year)

Part b already solved with same answer: 55358
